export const options = [
  { value: '', label: 'All' },
  { value: '20', label: 'Alabama' },
  { value: '21', label: 'Alaska' },
  { value: '22', label: 'Arizona' },
  { value: '23', label: 'Arkansas' },
  { value: '24', label: 'California' },
  { value: '25', label: 'Colorado' },
  { value: '26', label: 'Connecticut' },
  { value: '27', label: 'Delaware' },
  { value: '28', label: 'Florida' },
  { value: '29', label: 'Georgia' },
  { value: '30', label: 'Hawaii' },
  { value: '31', label: 'Idaho' },
  { value: '32', label: 'Illinois' },
  { value: '33', label: 'Indiana' },
  { value: '34', label: 'Iowa' },
  { value: '35', label: 'Kansas' },
  { value: '36', label: 'Kentucky' },
  { value: '37', label: 'Louisiana' },
  { value: '38', label: 'Maine' },
  { value: '39', label: 'Maryland' },
  { value: '40', label: 'Massachusetts' },
  { value: '41', label: 'Michigan' },
  { value: '42', label: 'Minnesota' },
  { value: '43', label: 'Mississippi' },
  { value: '44', label: 'Missouri' },
  { value: '45', label: 'Montana' },
  { value: '46', label: 'Nebraska' },
  { value: '47', label: 'Nevada' },
  { value: '48', label: 'New Hampshire' },
  { value: '49', label: 'New Jersey' },
  { value: '50', label: 'New Mexico' },
  { value: '51', label: 'New York' },
  { value: '52', label: 'North Carolina' },
  { value: '53', label: 'North Dakota' },
  { value: '54', label: 'Ohio' },
  { value: '55', label: 'Oklahoma' },
  { value: '56', label: 'Oregon' },
  { value: '57', label: 'Pennsylvania' },
  { value: '58', label: 'Rhode Island' },
  { value: '59', label: 'South Carolina' },
  { value: '60', label: 'South Dakota' },
  { value: '61', label: 'Tennessee' },
  { value: '62', label: 'Texas' },
  { value: '63', label: 'Utah' },
  { value: '64', label: 'Vermont' },
  { value: '65', label: 'Virginia' },
  { value: '66', label: 'Washington' },
  { value: '67', label: 'West Virginia' },
  { value: '68', label: 'Wisconsin' },
  { value: '69', label: 'Wyoming' },
]
